"use strict";
let car = "subaru";
let car1 = "mehran";
console.log("Is car == 'subaru'? I predict true");
console.log(car == "subaru");
console.log("Is car == 'toyota'? I predict false");
console.log(car == "toyota");
console.log("IS car == 'suzuki'? I predict false");
console.log(car == "suzuki");
console.log("IS car == 'mehran'? I predict true");
console.log(car1 == "mehran");
